### ISSUE TITLE
[ENHANCEMENT]: Allow Missing Shard-Group Duration

### ISSUE THREAD

**Issue by PeterBurner** [slcp/terraform-provider-influxdb-v2#36]
## Description

There are some API incompatibilities between Influx Cloud Serverless and Influx OSS. One is sharding.
InfluxDB Cloud Serverless does not allow one to configure sharding. It results in the error `error creating bucket: not implemented: specifying shard-group duration is not supported`.

## Proposal

You are currently assigning a default shard-group duration when the parameter is missing in the Terraform config. Could you please introduce a way to not set it at all? Something like if `shard_group_duration_seconds == null` then do not set `ShardGroupDurationSeconds`? If null is undistinguishable from the parameter being missing in the Terraform config, you could instead check if `shard_group_duration_seconds == -1`.

## Links

 - https://docs.influxdata.com/influxdb/cloud-serverless/reference/cli/influx/bucket/create/#create-a-bucket-with-a-custom-shard-group-duration

**Comment by slcp** [comment]
I might need to pay attention to the Influx Cloud API docs going forward, there seems to be some differences. As you can probably guess I didn't use it :)

The reason for setting the default duration when it is missing is to ensure that it is unset from non default value if it is removed.

Another option in addition to those you suggested would be to always do nothing on create if it isn't set, and inspect the previous value on update. I'll have a look and think, feel to raise a PR in the meantime.

**Comment by PeterBurner** [comment]
> Another option in addition to those you suggested would be to always do nothing on create if it isn't set

True. However I didn't want to suggest a solution that could potentially introduce a breaking change.

Thanks for looking into it.

**Comment by slcp** [comment]
I don't think that it would, Influx will set the default itself on create if not specified. The behavior on update would preserve the existing behavior as well. I'll have a play when I get a chance.

**Comment by slcp** [comment]
I've been having a read of the [API docs](https://docs.influxdata.com/influxdb/cloud/api/v2/#operation/PostBuckets) for Influx 2 Cloud and it claims to support `shardGroupDurationSeconds` on bucket creation/update. Am I looking at the correct API docs? If so, are not accurate?

**Comment by slcp** [comment]
I'm thinking that some value like `-1` might be the way to go for now to signal not manage the shard group duration in any way. Looking ahead, if this provider develops more in any significant way being able to flag the type of Influx host to the provider when its created might be a direction to go in. That way it is more explicit and sensible defaults can be managed internally based on the type of target.

**Comment by PeterBurner** [comment]
Sorry for not being specific enough. I am talking about Influx Cloud Serverless.
I updated the description accordingly.

**Comment by slcp** [comment]
Looks like the [API docs](https://docs.influxdata.com/influxdb/cloud-serverless/api/v2/#operation/PostBuckets) are just generally not very good, they are same for all versions :(
