### ISSUE TITLE
[FEATURE]: Make Server Check Configurable

### ISSUE THREAD

**Issue by PeterBurner** [slcp/terraform-provider-influxdb-v2#9]
## Description

There are some API incompatibilities between Influx Cloud and Influx OSS. One is the availability check.
The InfluxDB Go Client supports both ways. `Ready()` works on Influx OSS, `Ping()` works on Influx Cloud.
Could you please make it configurable which function to use for server availability check?

**Comment by slcp** [comment]
I've just seen this :) that sounds reasonable, happy to accept a PR if someone want to get to this before I do.

**Comment by slcp** [comment]
Closed with #29, released in v0.5.3.
